<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault><AvaloniaNameGeneratorIsEnabled>false</AvaloniaNameGeneratorIsEnabled></PropertyGroup><ItemGroup><ProjectReference Include="../../SharpRail.Plugins.Api.UI/SharpRail.Plugins.Api.UI.csproj" /><ProjectReference Include="../../SharpRail.Plugins.UI.Kit/SharpRail.Plugins.UI.Kit.csproj" /><ProjectReference Include="../Contract/SharpRail.Plugins.Blueprint.csproj" /><ProjectReference Include="..\..\SharpRail.Plugins.SpecDialect\Contract\SharpRail.Plugins.SpecDialect.csproj" /></ItemGroup></Project>
