<Project>
  <PropertyGroup><ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally></PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Headless" Version="12.1.3" />
    <PackageVersion Include="Avalonia.Skia" Version="12.1.3" />
    <PackageVersion Include="SkiaSharp" Version="4.148.0" />
    <PackageVersion Include="HarfBuzzSharp" Version="14.2.0" />
    <PackageVersion Include="protobuf-net.Grpc" Version="1.3.14" />
    <PackageVersion Include="protobuf-net.Grpc.AspNetCore" Version="1.3.14" />
    <PackageVersion Include="Grpc.Net.Client" Version="2.84.0" />
    <PackageVersion Include="Markdig" Version="1.4.0" />
    <PackageVersion Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.17" />
  </ItemGroup>
</Project>
