<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Contract/SharpRail.Plugins.Visualize.csproj" />
    <ProjectReference Include="../../SharpRail.Plugins.Api.Host/SharpRail.Plugins.Api.Host.csproj" />
    <InternalsVisibleTo Include="SharpRail.Checks" />
  </ItemGroup>
</Project>
