<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Contract/SharpRail.Plugins.FileIcons.csproj" />
    <ProjectReference Include="../../SharpRail.Plugins.Api.UI/SharpRail.Plugins.Api.UI.csproj" />
    <InternalsVisibleTo Include="SharpRail.Checks" />
  </ItemGroup>
</Project>
