<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
    <ProjectReference Include="../../SharpRail.Plugins.Api.Host/SharpRail.Plugins.Api.Host.csproj" />
    <ProjectReference Include="../Contract/SharpRail.Plugins.SpecDialect.csproj" />
  </ItemGroup>
</Project>
