// Regenerates the file-icons plugin's recoloured SVGs and its committed name table from the pinned
// material-icon-theme release, or with --check fails when either is stale. Run from the checkout root:
//   .tools/dotnet/dotnet run src/SharpRail.Plugins.FileIcons/scripts/generate-file-icons.cs [-- --check]
using System.Formats.Tar;
using System.Globalization;
using System.IO.Compression;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;

const string Version = "5.38.1";
const string ArchiveSha256 = "d4342dc13a24bd40c4f417337dc19d2d2c42e47f8bb42ca677109bce769f078e";
var assetsDirectory = Path.Combine(".tools", "file-icons", "assets", "file-icons");
var tablePath = Path.Combine("src", "SharpRail.Plugins.FileIcons", "UI", "FileIconTable.g.cs");
var check = args.Contains("--check");
var assetsOnly = args.Contains("--assets-only");

var archive = Path.Combine(".tools", "file-icons", $"material-icon-theme-{Version}.tgz");
if (!File.Exists(archive) || Sha256(archive) != ArchiveSha256)
{
    Directory.CreateDirectory(Path.GetDirectoryName(archive)!);
    using var http = new HttpClient();
    var partial = archive + ".partial";
    await File.WriteAllBytesAsync(partial, await http.GetByteArrayAsync($"https://registry.npmjs.org/material-icon-theme/-/material-icon-theme-{Version}.tgz"));
    if (Sha256(partial) != ArchiveSha256) { File.Delete(partial); Console.Error.WriteLine("Unexpected material-icon-theme archive checksum"); return 1; }
    File.Move(partial, archive, overwrite: true);
}

var svgs = new SortedDictionary<string, string>(StringComparer.Ordinal);
JsonElement manifest = default;
await using (var gzip = new GZipStream(File.OpenRead(archive), CompressionMode.Decompress))
using (var tar = new TarReader(gzip))
    while (tar.GetNextEntry() is { } entry)
    {
        if (entry.DataStream is null) continue;
        using var reader = new StreamReader(entry.DataStream, Encoding.UTF8);
        var text = reader.ReadToEnd();
        if (entry.Name == "package/dist/material-icons.json") manifest = JsonDocument.Parse(text).RootElement.Clone();
        else if (entry.Name.StartsWith("package/icons/", StringComparison.Ordinal) && entry.Name.EndsWith(".svg", StringComparison.Ordinal))
            svgs[Path.GetFileNameWithoutExtension(entry.Name)] = Monotone(text).Trim() + "\n";
    }

SortedDictionary<string, string> Lower(string property)
{
    var table = new SortedDictionary<string, string>(StringComparer.Ordinal);
    foreach (var item in manifest.GetProperty(property).EnumerateObject())
        if (item.Value.GetString() is { } icon && svgs.ContainsKey(icon)) table[item.Name.ToLowerInvariant()] = icon;
    return table;
}

var literal = new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };
string Entries(SortedDictionary<string, string> table) =>
    string.Concat(table.Select(entry => $"        [{JsonSerializer.Serialize(entry.Key, literal)}] = {JsonSerializer.Serialize(entry.Value, literal)},\n"));

var source = $$"""
    // <auto-generated/>
    // Generated by src/SharpRail.Plugins.FileIcons/scripts/generate-file-icons.cs from material-icon-theme v{{Version}}. Do not edit.
    #nullable enable
    using System.Collections.Frozen;

    namespace SharpRail.Plugins.FileIcons.UI;

    internal static class FileIconTable
    {
        public const string Version = "{{Version}}";

        public const string Fallback = {{JsonSerializer.Serialize(manifest.GetProperty("file").GetString())}};

        // Whole filenames, which win over an extension: vitest.config.ts is not a TypeScript file icon.
        public static readonly FrozenDictionary<string, string> ByName = new Dictionary<string, string>
        {
    {{Entries(Lower("fileNames"))}}    }.ToFrozenDictionary();

        // Longest extension first at lookup time, so d.ts beats ts.
        public static readonly FrozenDictionary<string, string> ByExtension = new Dictionary<string, string>
        {
    {{Entries(Lower("fileExtensions"))}}    }.ToFrozenDictionary();
    }

    """;

if ((check || assetsOnly) && (!File.Exists(tablePath) || File.ReadAllText(tablePath).ReplaceLineEndings("\n") != source))
{
    Console.Error.WriteLine("file icons: the committed table is stale; regenerate it from the pinned release.");
    return 1;
}

if (check)
{
    var stale = !File.Exists(tablePath) || File.ReadAllText(tablePath).ReplaceLineEndings("\n") != source;
    var onDisk = Directory.Exists(assetsDirectory) ? Directory.GetFiles(assetsDirectory, "*.svg") : [];
    stale |= onDisk.Length != svgs.Count || svgs.Any(svg => !File.Exists(Path.Combine(assetsDirectory, svg.Key + ".svg")) ||
        File.ReadAllText(Path.Combine(assetsDirectory, svg.Key + ".svg")) != svg.Value);
    if (stale) { Console.Error.WriteLine("file icons: STALE; run .tools/dotnet/dotnet run src/SharpRail.Plugins.FileIcons/scripts/generate-file-icons.cs and commit the result."); return 1; }
    Console.WriteLine($"file icons: up to date (v{Version})");
    return 0;
}
if (!assetsOnly) File.WriteAllText(tablePath, source);
if (Directory.Exists(assetsDirectory)) Directory.Delete(assetsDirectory, recursive: true);
Directory.CreateDirectory(assetsDirectory);
foreach (var (name, svg) in svgs) File.WriteAllText(Path.Combine(assetsDirectory, name + ".svg"), svg);
Console.WriteLine($"file icons: wrote {svgs.Count} recoloured icons and the name table (v{Version})");
return 0;

static string Sha256(string path)
{
    using var stream = File.OpenRead(path);
    return Convert.ToHexStringLower(SHA256.HashData(stream));
}

// Material's icons are one or two flat colours: a saturated primary and a pale accent. Both become the theme's
// own colour, the paler one at reduced alpha, so the shape keeps its two-tone reading wherever it is drawn. A
// gradient cannot be split that way and flattens to the primary.
static string Monotone(string svg)
{
    var colour = new Regex("(fill|stroke|stop-color)=\"(#[0-9a-fA-F]{3,8})\"");
    var colours = colour.Matches(svg).Select(match => match.Groups[2].Value).Distinct().ToList();
    var sorted = colours.OrderBy(Luminance).ToList();
    var median = sorted.Count > 1 ? Luminance(sorted[sorted.Count / 2]) : 1;
    var secondary = colours.Where(value => sorted.Count > 1 && Luminance(value) >= median).ToHashSet();
    svg = Regex.Replace(svg, "<defs>[\\s\\S]*?</defs>", "");
    svg = Regex.Replace(svg, "(fill|stroke)=\"url\\(#[^)]*\\)\"", match => $"{match.Groups[1].Value}=\"currentColor\"");
    return colour.Replace(svg, match =>
        $"{match.Groups[1].Value}=\"currentColor\"" + (secondary.Contains(match.Groups[2].Value) ? $" {match.Groups[1].Value}-opacity=\".45\"" : ""));
}

static double Luminance(string hex)
{
    var value = hex[1..];
    int Channel(int index) => value.Length <= 4
        ? int.Parse(new string(value[index], 2), NumberStyles.HexNumber)
        : int.Parse(value.Substring(index * 2, 2), NumberStyles.HexNumber);
    return (0.2126 * Channel(0) + 0.7152 * Channel(1) + 0.0722 * Channel(2)) / 255;
}
