<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault><AvaloniaNameGeneratorIsEnabled>false</AvaloniaNameGeneratorIsEnabled></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../SharpRail.Scintilla/SharpRail.Scintilla.csproj" />
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="TextMateSharp" />
    <PackageReference Include="TextMateSharp.Grammars" />
    <InternalsVisibleTo Include="SharpRail.Checks" />
    <InternalsVisibleTo Include="SharpRail.UI" />
    <EmbeddedResource Include="Editor/Grammars/*.json" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" PrivateAssets="all" />
    <AvaloniaResource Include="Assets/**" />
  </ItemGroup>
</Project>
