// Regenerates CodexConfigKeys.cs from Codex's configuration reference, keeping only each key and its type.
// Run by hand from this directory and read the diff: `dotnet run GenerateConfigKeys.cs`, or `-- --check` to compare.
using System.Net;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.RegularExpressions;

const string source = "https://learn.chatgpt.com/docs/config-file/config-reference";
var target = Path.GetFullPath(Path.Combine(AppContext.GetData("EntryPointFileDirectoryPath") as string ?? ".", "..", "CodexConfigKeys.cs"));

using var http = new HttpClient();
using var response = await http.GetAsync(source);
if (!response.IsSuccessStatusCode)
{
    Console.Error.WriteLine($"could not read {source}: {(int)response.StatusCode}");
    return 1;
}
var html = await response.Content.ReadAsStringAsync();
var rows = new List<(string Key, string Type)>();
var seen = new HashSet<string>();
foreach (Match match in Regex.Matches(html, "&quot;key&quot;:\\[0,&quot;(.*?)&quot;\\],&quot;type&quot;:\\[0,&quot;(.*?)&quot;\\]"))
{
    var key = WebUtility.HtmlDecode(match.Groups[1].Value);
    if (!seen.Add(key)) break;
    rows.Add((key, WebUtility.HtmlDecode(match.Groups[2].Value)));
}
if (rows.Count < 50)
{
    Console.Error.WriteLine($"only {rows.Count} keys parsed; the reference's shape changed, so fix the parser");
    return 1;
}

var rendered = new StringBuilder();
rendered.Append("""
    // The config.toml keys Codex documents and the type its reference gives each, nothing else: the
    // descriptions are OpenAI's prose and stay where they are maintained; the pane links to them.
    // Generated by `dotnet run scripts/GenerateConfigKeys.cs`, run by hand and its diff read; see SPEC.md.

    namespace SharpRail.Plugins.Codex;

    public static class CodexConfigKeys
    {

    """);
rendered.Append($"    public const string DocsUrl = \"{source}\";\n\n");
rendered.Append("    public static readonly IReadOnlyList<KeyValuePair<string, string>> All =\n    [\n");
var json = new JsonSerializerOptions { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };
foreach (var (key, type) in rows) rendered.Append($"        new({JsonSerializer.Serialize(key, json)}, {JsonSerializer.Serialize(type, json)}),\n");
rendered.Append("    ];\n}\n");

if (args.Contains("--check"))
{
    var current = File.Exists(target) ? File.ReadAllText(target) : "";
    if (current != rendered.ToString())
    {
        Console.Error.WriteLine("CodexConfigKeys.cs is out of date with the reference");
        return 1;
    }
    return 0;
}
File.WriteAllText(target, rendered.ToString());
Console.WriteLine($"{rows.Count} keys -> {target}");
return 0;
