using System.Globalization;
using System.Text;
using System.Text.Json;

using SharpRail.UI.Rendering;

namespace SharpRail.Checks.Design;

/// <summary>The authored design sources under Rendering/Design and the C# generated from them.</summary>
internal static class DesignSources
{
    internal sealed record ColorRole(string Name, string From, string? Alpha, bool IsColor);
    internal sealed record Effect(string Name, string Dark, string Light);
    internal sealed record Colors(IReadOnlyDictionary<string, int> Scale, IReadOnlyList<ColorRole> Roles, IReadOnlyList<Effect> Effects,
        IReadOnlyList<string> Unclaimed);

    /// <summary>The checkout holding the sources, or null when the checks run away from one (a copied publish).</summary>
    internal static string? Root()
    {
        foreach (var start in new[] { Directory.GetCurrentDirectory(), AppContext.BaseDirectory })
            for (var directory = new DirectoryInfo(start); directory is not null; directory = directory.Parent)
                if (File.Exists(Path.Combine(directory.FullName, "SharpRail.slnx"))) return directory.FullName;
        return null;
    }

    internal static string Ui(string root) => Path.Combine(root, "src", "SharpRail.UI");
    internal static string Source(string root, string name) => Path.Combine(Ui(root), "Rendering", "Design", name);
    internal static string Generated(string root, string name) => Path.Combine(root, "src", "SharpRail.Plugins.UI.Kit", "Generated", name);

    internal static Colors LoadColors(string root)
    {
        using var json = JsonDocument.Parse(File.ReadAllText(Source(root, "colors.json")));
        var document = json.RootElement;
        static string? Optional(JsonElement element, string name) => element.TryGetProperty(name, out var value) ? value.GetString() : null;
        return new(
            document.GetProperty("scale").EnumerateObject().ToDictionary(step => step.Name, step => step.Value.GetInt32()),
            [.. document.GetProperty("roles").EnumerateObject().Select(role => new ColorRole(role.Name,
                role.Value.GetProperty("from").GetString()!, Optional(role.Value, "alpha"), Optional(role.Value, "kind") == "color"))],
            [.. document.GetProperty("effects").EnumerateObject().Select(effect => new Effect(effect.Name,
                effect.Value.GetProperty("dark").GetString()!, effect.Value.GetProperty("light").GetString()!))],
            [.. document.GetProperty("unclaimed").EnumerateObject().Select(key => key.Name)]);
    }

    internal sealed record SpacingException(string File, string Value);

    internal static (IReadOnlyList<double> Steps, IReadOnlyList<SpacingException> Exceptions) LoadSpacing(string root)
    {
        using var json = JsonDocument.Parse(File.ReadAllText(Source(root, "spacing.json")));
        return ([.. json.RootElement.GetProperty("steps").EnumerateArray().Select(step => step.GetDouble())],
            [.. json.RootElement.GetProperty("exceptions").EnumerateArray().Select(entry =>
                new SpacingException(entry.GetProperty("file").GetString()!, entry.GetProperty("value").GetString()!))]);
    }

    /// <summary>Every generated file by name, as it should currently read.</summary>
    internal static IReadOnlyDictionary<string, string> Generate(string root) => new Dictionary<string, string>
    {
        ["Ui.Colors.g.cs"] = GenerateColors(LoadColors(root))
    };

    private const string Header = "// <auto-generated>\n// Written from Rendering/Design/{0} by `SharpRail.Checks -- --design --write`. Edit the source, not this file.\n// </auto-generated>\n";

    private static string GenerateColors(Colors colors)
    {
        var text = new StringBuilder(string.Format(CultureInfo.InvariantCulture, Header, "colors.json"));
        text.Append("#nullable enable\nusing Avalonia.Media;\n\nnamespace SharpRail.Plugins.UI.Kit;\n\npublic static partial class Ui\n{\n");
        foreach (var role in colors.Roles)
            text.Append(role.IsColor
                ? $"    public static Color{(Nullable(role) ? "?" : "")} {role.Name} {{ get; private set; }}\n"
                : $"    public static readonly SolidColorBrush {role.Name} = new();\n");
        foreach (var effect in colors.Effects) text.Append($"    public static readonly SolidColorBrush {effect.Name} = new();\n");
        text.Append("\n    private static void ApplyRoles(ThemeManifest theme)\n    {\n");
        foreach (var role in colors.Roles)
        {
            var source = Nullable(role) ? $"theme.Colors[\"{role.From}\"]" : $"theme[\"{role.From}\"]";
            if (role.Alpha is not null) source = $"Alpha({source}, {colors.Scale[role.Alpha]})";
            text.Append($"        {role.Name}{(role.IsColor ? "" : ".Color")} = {source};\n");
        }
        foreach (var effect in colors.Effects)
            text.Append(effect.Dark == effect.Light
                ? $"        {effect.Name}.Color = {Argb(effect.Dark)};\n"
                : $"        {effect.Name}.Color = theme.IsLight ? {Argb(effect.Light)} : {Argb(effect.Dark)};\n");
        return text.Append("    }\n}\n").ToString();
    }

    internal static bool Nullable(ColorRole role) => Themes.NullableKeys.Contains(role.From);

    // #rrggbbaa as the #aarrggbb number Avalonia reads.
    private static string Argb(string hex) => $"Color.FromUInt32(0x{hex[7..9]}{hex[1..7]})";
}