<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Contract/SharpRail.Plugins.Discord.csproj" />
    <ProjectReference Include="../../SharpRail.Plugins.Api.Host/SharpRail.Plugins.Api.Host.csproj" />
    <InternalsVisibleTo Include="SharpRail.Checks" />
    <Content Include="../assets/**" LinkBase="plugins/discord/assets" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
